global using System.ComponentModel;
global using ToolBox.Geral.Interfaces;
global using BibliotecaPublica.Extensoes.Extensoes;
global using BibliotecaPublica.Geral.Estruturas;
global using ToolBox.Geral;
global using BibliotecaPublica.Geral.Enumeracoes;
global using BibliotecaPublica.Notificacoes;
global using BibliotecaPublica.Notificacoes.Enums;
global using FluentValidation.Results;