global using System.ComponentModel;
global using ToolBox.Geral.Interfaces;
global using BibliotecaPublica.Extensoes.Extensoes;
global using BibliotecaPublica.Core.Structs;
global using ToolBox.Geral;
global using BibliotecaPublica.Core.Enums;
global using BibliotecaPublica.Notificacoes;
global using BibliotecaPublica.Notificacoes.Enums;
global using FluentValidation.Results;