global using BibliotecaPublica.BibliotecaPublicaFramework;
global using BibliotecaPublica.BibliotecaPublicaFramework.Classes.Servicos.Conversores;
global using BibliotecaPublica.BibliotecaPublicaFramework.Classes.Verificadores;
global using BibliotecaPublica.BibliotecaPublicaFramework.Enums;
global using BibliotecaPublica.BibliotecaPublicaFramework.Estruturas;
global using System.ComponentModel;
global using ToolBox.ToolBoxWinForms.Net6.Enums;
global using ToolBox.ToolBoxWinForms.Net6.Interfaces;